version: '2'

services:
  database:
    image: postgres:10
    environment:
      - POSTGRES_USER=golds
      - POSTGRES_PASSWORD=golds
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    ports:
      - 5432:5432